# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:

  # redis_client:
  #   class: 'Predis\Client'

  # redis_cache:
  #   class: 'Snc\RedisBundle\Doctrine\Cache\RedisCache'
  #   arguments:
  #     - '@redis_client'

  # snc_second_level_cache:
  #   class: '%snc_redis.doctrine_cache_predis.class%'
  #   arguments: [ '@snc_redis.doctrine' ]

  mailer_service:
    class: AppBundle\Repository\MailerService
    lazy: true
    autowire: true

  employees_repository:
    class: AppBundle\Repository\EmployeesRepository
    lazy: true
    autowire: true

  employees_repository_decorating:
    class: AppBundle\Repository\EmployeesRepositoryDecorating
    lazy: true
    decorates: employees_repository
    public: false
    # autowire: true
    arguments:
      - '@employees_repository_decorating.inner'
      - '@event_dispatcher'
      # - '@knp_paginator'
      # - '@serializer'

  employees_form_type:
    class: AppBundle\Form\EmployeesType
    autowire: true
    tags:
      - { name: form.type }

  employees_search_form_type:
    class: AppBundle\Form\EmployeesSearchType
    autowire: true
    tags:
      - { name: form.type }

  employees_save_subscriber:
    class: AppBundle\Event\EmployeesSaveEventSubscriber
    autowire: true
    lazy: true
    tags:
      - { name: kernel.event_subscriber }

  employees_search_subscriber:
    class: AppBundle\Event\EmployeesSearchEventSubscriber
    autowire: true
    lazy: true
    tags:
      - { name: kernel.event_subscriber }

  doctrine_subscriber:
    class: AppBundle\Event\DoctrineSubscriber
    lazy: true
    autowire: true
    tags:
      - { name: doctrine.event_subscriber }

  security_subscriber:
    class: AppBundle\Event\SecuritySubscriber
    # lazy: true
    autowire: true
    tags:
      - { name: kernel.event_subscriber }

  # get_set_method_normalizer:
  #   class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer
  #   public: false
  #   tags:
  #     - { name: serializer.normalizer }

  # array_denormalizer:
  #   class: Symfony\Component\Serializer\Normalizer\ArrayDenormalizer
  #   public: false
  #   tags:
  #     - { name: serializer.normalizer }

  fire.event.service:
    class: AppBundle\AsyncTask\FireEventService
    arguments: ["@enqueue.producer"]

  event.processor.service:
    class: AppBundle\AsyncTask\EventProcessor
    autowire: true
    tags:
      - { name: 'enqueue.command_subscriber' }